<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Core_Logic">
      <HintPath>..\Core_Logic\bin\Debug\net8.0\Core_Logic.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
